/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LocalDemoRouteRouteImport } from './routes/local-demo/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocalDemoIndexRouteImport } from './routes/local-demo/index'
import { Route as QTokenRouteImport } from './routes/q/$token'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppItemsRouteImport } from './routes/_app/items'
import { Route as AppQuotesIndexRouteImport } from './routes/_app/quotes/index'
import { Route as AppQuotesNewRouteImport } from './routes/_app/quotes/new'
import { Route as AppQuotesIdRouteImport } from './routes/_app/quotes/$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalDemoRouteRoute = LocalDemoRouteRouteImport.update({
  id: '/local-demo',
  path: '/local-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalDemoIndexRoute = LocalDemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocalDemoRouteRoute,
} as any)
const QTokenRoute = QTokenRouteImport.update({
  id: '/q/$token',
  path: '/q/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppItemsRoute = AppItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuotesIndexRoute = AppQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuotesNewRoute = AppQuotesNewRouteImport.update({
  id: '/quotes/new',
  path: '/quotes/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuotesIdRoute = AppQuotesIdRouteImport.update({
  id: '/quotes/$id',
  path: '/quotes/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/local-demo': typeof LocalDemoRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/items': typeof AppItemsRoute
  '/settings': typeof AppSettingsRoute
  '/q/$token': typeof QTokenRoute
  '/local-demo/': typeof LocalDemoIndexRoute
  '/quotes/$id': typeof AppQuotesIdRoute
  '/quotes/new': typeof AppQuotesNewRoute
  '/quotes/': typeof AppQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/items': typeof AppItemsRoute
  '/settings': typeof AppSettingsRoute
  '/q/$token': typeof QTokenRoute
  '/local-demo': typeof LocalDemoIndexRoute
  '/quotes/$id': typeof AppQuotesIdRoute
  '/quotes/new': typeof AppQuotesNewRoute
  '/quotes': typeof AppQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/local-demo': typeof LocalDemoRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/items': typeof AppItemsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/q/$token': typeof QTokenRoute
  '/local-demo/': typeof LocalDemoIndexRoute
  '/_app/quotes/$id': typeof AppQuotesIdRoute
  '/_app/quotes/new': typeof AppQuotesNewRoute
  '/_app/quotes/': typeof AppQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/local-demo'
    | '/auth'
    | '/reset-password'
    | '/items'
    | '/settings'
    | '/q/$token'
    | '/local-demo/'
    | '/quotes/$id'
    | '/quotes/new'
    | '/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/items'
    | '/settings'
    | '/q/$token'
    | '/local-demo'
    | '/quotes/$id'
    | '/quotes/new'
    | '/quotes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/local-demo'
    | '/auth'
    | '/reset-password'
    | '/_app/items'
    | '/_app/settings'
    | '/q/$token'
    | '/local-demo/'
    | '/_app/quotes/$id'
    | '/_app/quotes/new'
    | '/_app/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LocalDemoRouteRoute: typeof LocalDemoRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  QTokenRoute: typeof QTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-demo': {
      id: '/local-demo'
      path: '/local-demo'
      fullPath: '/local-demo'
      preLoaderRoute: typeof LocalDemoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-demo/': {
      id: '/local-demo/'
      path: '/'
      fullPath: '/local-demo/'
      preLoaderRoute: typeof LocalDemoIndexRouteImport
      parentRoute: typeof LocalDemoRouteRoute
    }
    '/q/$token': {
      id: '/q/$token'
      path: '/q/$token'
      fullPath: '/q/$token'
      preLoaderRoute: typeof QTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/items': {
      id: '/_app/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AppItemsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/quotes/': {
      id: '/_app/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AppQuotesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/quotes/new': {
      id: '/_app/quotes/new'
      path: '/quotes/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof AppQuotesNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/quotes/$id': {
      id: '/_app/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof AppQuotesIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppItemsRoute: typeof AppItemsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppQuotesIdRoute: typeof AppQuotesIdRoute
  AppQuotesNewRoute: typeof AppQuotesNewRoute
  AppQuotesIndexRoute: typeof AppQuotesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppItemsRoute: AppItemsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppQuotesIdRoute: AppQuotesIdRoute,
  AppQuotesNewRoute: AppQuotesNewRoute,
  AppQuotesIndexRoute: AppQuotesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface LocalDemoRouteRouteChildren {
  LocalDemoIndexRoute: typeof LocalDemoIndexRoute
}

const LocalDemoRouteRouteChildren: LocalDemoRouteRouteChildren = {
  LocalDemoIndexRoute: LocalDemoIndexRoute,
}

const LocalDemoRouteRouteWithChildren = LocalDemoRouteRoute._addFileChildren(
  LocalDemoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LocalDemoRouteRoute: LocalDemoRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  QTokenRoute: QTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
